dist: xenial
language: python
python:
  # - 3.6
  # - 3.7
  - 3.8
  # - 3.9-dev
before_install:
  - sudo apt-get install graphviz
install:
  - pip install -e .[dev]
script:
  - coverage run --source=hubit -m unittest discover -s ./tests -p "*_test.py"
  - coverage report -m  
# - black --check .
# - mypy hubit
# - pylint hubit
after_success:
  coveralls
stages:
  - test
branches:
  only:
  - master
  - develop