dist: focal
language: python
python:
- 3.7
- 3.8
- 3.9
before_install:
- sudo apt-get install graphviz
- python -m pip install --upgrade pip
install:
- pip install -e .[dev]
script:
- coverage run --source=hubit -m pytest ./tests
- coverage report -m
- black --version
- black --check .
- mypy --version
- mypy hubit
after_success: coveralls
stages:
- test
- deploy
branches:
  only:
    - master
    - /\d+\.\d+\.\d+$/
jobs:
  include:
  - stage: test
    script: skip
  - stage: deploy
    script: skip
    python: 3.8
    deploy:
      provider: pypi
      user: __token__
      password:
        secure: L2ZMhXZ1aJSZoR9nCVDQhuQvG21BL1xJvAx4sn5S8l7qlHI9q70LZXUmRoAt5A/hmBfL13LBjtlxgL4PdN4AFb9ji6zrvMMy6Onts6ftjz9nyc/AxKevtbsJxSn6a/T9jsxskAB3iDldnAKtn56OIGo4JYgBRnqliGbbG1w2Kb+Oo8hBHOtFSSLi3Xp4WO8WLtz4E4G0fjY7vh+gwhY1dMhP0h0ZRauXDRRhAZIizhwt2zLIILXtO0OEMnjoHbGKW8cRApoepdOzeTiplXe9hLMazK5U8PR4b2hve1lsExml95BvkGBoMxEzWQH0JBNgiVqYZMnkplSAx8e6Eit9Yucjn7iFnJbf/w2fJkdM0Q6i9hKtZ1912fAIL7qIrZpeZvNsk5+etDgrBKMkYIGCxiuLOOujkt4g77nkyZimyB9nmUPteiMPGFAX+Izi+0g2yGp3SrBJcAf1HWvlroC/igzga5v9z8T3py4X3XWB7J6CWMUGupWAnAYFG5sHxe89aBc3lTkFSK9HQLKbjKhABeU07oiiEVBZJgep0VGzqh11vzOzPaGavDSjZ0Dvc1Q4UbkX2bSkDDbMcLHs5Dv4nQ/zvE/0TfRQ/TnC4qlci42Re2BOXELhMDnPhf3Z9Rq9STa/894JOEhDoP2Gk/8k8to1uvcrhKWRca9fx/vqPAc=
      on:
        tags: true
      distributions: sdist bdist_wheel
