site_name: Hubit Docs

theme:
  name: "material"

plugins:
  - search
  - autorefs
  - mkdocstrings:
      watch: 
        - hubit
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: false
nav:
    - Home: index.md
    - Installation: installation.md
    - Code Reference:
        - Config: config-reference.md
        - Model: model-reference.md

