site_name: Hubit Docs

theme:
  name: "material"

plugins:
  - search
  - autorefs
  - macros
  - mkdocstrings:
      watch: 
        - hubit
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: false
nav:
    - Home: index.md
    - Installation: installation.md
    - Code Reference:
        - Hubit: hubit-reference.md
        - Hubit model: model-reference.md
        - Model config: config-reference.md
        - Model log: log-reference.md

# extra:
#   version: 0.3.0
