site_name: My Docs

theme:
  name: "material"

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: false
nav:
    - Home: index.md
    - Installation: installation.md
    - Code Reference:
        - Config: config-reference.md

