name: docs
on:
  push:
    branches:
      - master
      - '*'
  # pull_request:
  #   branches: [master]
  # push:
  #   tags:
  #     - '*'
jobs:
  deploy:
    name: Build and Deploy Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2'

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
      - run: | 
          ls -ltr
          pip install mkdocs-material
          pip install mkdocstrings
          pip install mkdocs-macros-plugin

      - name: Build docs
        run: |
          git pull
          mkdocs gh-deploy --force # python -m mkdocs gh-deploy