name: docs
on:
  # push:
  #   branches:
  #     - master
  #     - '*'
  # pull_request:
  #   branches: [master]
  push:
    tags:
      - '*'
jobs:
  deploy:
    name: Build and Deploy Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Get some info 
        run: |
          pwd
          ls -ltr
          python setup.py --version
          python -c "import sys; print(sys.path)"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material
          pip install mkdocstrings
          pip install mkdocs-macros-plugin

      - name: Build docs
        run: |
          mkdocs gh-deploy --force
