name: docs
on:
  push:
    branches:
      - master
      - '*'
  # pull_request:
  #   branches: [master]
  # push:
  #   tags:
  #     - '*'
jobs:
  deploy:
    name: Build and Deploy Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          export PYTHONPATH="$PWD/hubit"
          pwd
          ls -ltr
          python -m pip install --upgrade pip
          pip install mkdocs-material
          pip install mkdocstrings
          pip install mkdocs-macros-plugin

      - name: Build docs
        run: |
          python -c "import sys; print(sys.path)"
          mkdocs gh-deploy --force
